version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: common-db
      MYSQL_ROOT_PASSWORD: P@ssword123
    networks:
      - common_network

networks:
  common_network:
    driver: bridge

volumes:
  mysql_data:
